[tool.ruff]
target-version = "py311"
line-length = 120
# Rules to enable (see https://beta.ruff.rs/docs/rules/)
select = ["ALL"]
ignore = [
    # FIXME: This should be enabled, but doesn't seem to work.
    #   You can leave this disabled if isort is separately run.
    "I001", # (Import block is un-sorted of un-formatted)

    "D100", # (Missing docstring in public module)
    "D101", # (Missing docstring in public class)
    "D103", # (Missing docstring in public function)
    "D104", # (Missing docstring in public package)
    "D107", # (Missing docstring in `__init__`)
    "D203", # (1 blank line required before class docstring) (Reason: To prefer D203 for no blank line)
    "D212", # (Multi-line docstring summary should start at the first line) (Reason: To prefer D213 for second line)

    "ANN101", # (Missing type annotation for `self` in method)

    "A001", # (Variable is shadowing a Python builtin)
    "A002", # (Argument is shadowing a Python builtin)
    "A003", # (Class attribute is shadowing a Python builtin)

    "RET505", # (Unnecessary `{branch}` after `return` statement)
]

[tool.ruff.per-file-ignores]
"tests/**" = [
    "S101", # (Use of `assert` detected)
]

[tool.isort]
profile = "black"

[tool.black]
line_length = 120
