[tool.pylint]
max-line-length = 120
disable = [
    "C0114", # (missing-module-docstring)
    "C0115", # (missing-class-docstring)
    "C0116", # (missing-function-docstring)
    "W0511", # (fixme)
    "W0621", # (redefined-outer-name)
    "W0622", # (redefined-builtin)
    "R0903", # (too-few-public-methods)
    "R1705", # (no-else-return)
]
good-names=["db","id"]

[tool.vulture]
paths = ["run.py", "ims"]
sort_by_size = true
ignore_decorators = ["@flask_app.route"]
min_confidence = 61

[tool.mypy]
strict = true

[tool.black]
line_length = 120

[tool.isort]
line_length = 120
